fix: added support in TestRunExistingResourcesInstances  test to use unique prefix
terraform-ibm-modules/terraform-ibm-scc pull request #167
Opened 2024-09-23 12:55 UTC by Khuzaima05

### Description

- added support in TestRunExistingResourcesInstances  test to use unique prefix
- added a validation in cos block to prevent COS creation if existing SCC is passed, to avoid bucket conflict.

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-09-23 12:55 UTC, Khuzaima05 commented
/run pipeline

2024-09-24 16:02 UTC, Khuzaima05 commented
/run pipeline

2024-09-24 17:18 UTC, Khuzaima05 commented
@ocofaigh , I've resolved all the review comments, could you please review again?

2024-09-24 17:42 UTC, ocofaigh commented
@Khuzaima05 The pipeline is failing - please check

2024-09-24 17:47 UTC, ocofaigh commented on main.tf
> +  count                       = var.existing_scc_instance_crn != null || var.skip_cos_iam_authorization_policy ? 0 : 1
I think you should update the variable description of `skip_cos_iam_authorization_policy` to explicitly call out that the value is ignored if passing an existing SCC instance.

2024-09-30 07:49 UTC, Khuzaima05 commented
/run pipeline

2024-09-30 08:17 UTC, Khuzaima05 commented
@ocofaigh ,
Upgrade test is failing, I have tested it manually apply and re-apply.
This is the change which is happening:
<img width="1637" alt="Screenshot 2024-09-30 at 1 44 35 PM" src="https://github.com/user-attachments/assets/97cc23bb-1ccf-4708-859e-e527fcfc5a04">

Can I skip the upgrade test?

2024-10-07 08:34 UTC, ocofaigh requested changes
@Khuzaima05 In the complete example, you added a count to the cos module. So hence the statefile in the upgrade test now thinks it needs to recreate the COS instance and bucket. Because they are getting recreated, the SCC settings and the auth policy have been identified for updates with the new COS details.

We have 2 options..
1. add a moved block to the example to prevent COS from being recreated
2. skip upgrade test

Usually I would say there is no need to add a moved block to an example, but I think I would like to see the upgrade test pass here to ensure we don’t have any other issues. So suggest to add that to the example (add it in a `moved.tf` file) just for this PR, and we can remove it in a follow up PR.

2024-10-07 09:00 UTC, Khuzaima05 commented
/run pipeline

2024-10-07 09:10 UTC, Khuzaima05 commented
/run pipeline

2024-10-07 09:27 UTC, ocofaigh approved these changes

2024-10-07 09:28 UTC, merged

2024-10-07 09:29 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 1.8.12 :tada:

The release is available on [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-scc/releases/tag/v1.8.12)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: